### ISSUE TITLE
Do not emit request code if the google api options is not defined

### ISSUE THREAD

**Issue by sue71** [sue71/protoc-gen-jsonpb-ts#43]
#34

**Comment by eqyiel** [comment]
This can happen for `.proto` files which define services, but have no `options.http` annotation.

Here's an example `.proto` file that can fail: https://github.com/eqyiel/protoc-gen-jsonpb-ts/commit/10466581d930c201d1095867dab9b6e7ee674ee2

And what happens when running `./example.sh`:

<details>

```
~/git/protoc-gen-jsonpb-ts fix/demonstrate-rpc-with-no-http-annotation* ⇡
❯ ./example.sh

> protoc-gen-jsonpb-ts@0.1.9 build /Users/r-maher/git/protoc-gen-jsonpb-ts
> npm run clean && ./node_modules/.bin/tsc


> protoc-gen-jsonpb-ts@0.1.9 clean /Users/r-maher/git/protoc-gen-jsonpb-ts
> rm -rf ./lib

npm WARN example@1.0.0 No description
npm WARN example@1.0.0 No repository field.

added 2 packages from 3 contributors, removed 14 packages and audited 4 packages in 1.18s
found 0 vulnerabilities

example/basic/dependency/dependency.proto:6:1: warning: Import google/type/date.proto is unused.
example/basic/service/example.proto:13:1: warning: Import google/protobuf/api.proto is unused.
example/basic/service/example.proto:14:1: warning: Import google/protobuf/type.proto is unused.
example/basic/service/example.proto:6:1: warning: Import example/basic/service/annotation.proto is unused.
example/basic/service/example.proto:24:1: warning: Import google/type/date.proto is unused.
example/basic/service/example.proto:10:1: warning: Import google/protobuf/source_context.proto is unused.
example/basic/service/example.proto:12:1: warning: Import google/protobuf/compiler/plugin.proto is unused.
{ TypeError: ejs:33
    31|
    32| <% serviceList.forEach( service => { %>
 >> 33| <%- include('/ts/service', { service, helper, filename: name, config }) %>
    34| <% }); %>
    35|
    36| <% messageTypeList.forEach( message => { %>

/Users/r-maher/git/protoc-gen-jsonpb-ts/templates/ts/service.ejs:3
    1| export namespace <%= service.name %> {
    2|   <% service.methodList.forEach( method => { _%>
 >> 3|   <%- include('method', { method, helper }) _%>
    4|   <% }); %>
    5| }

/Users/r-maher/git/protoc-gen-jsonpb-ts/templates/ts/method.ejs:1
 >> 1| <%
    2|   const {
    3|     options,
    4|     name,

Cannot read property 'http' of undefined
    at eval (/Users/r-maher/git/protoc-gen-jsonpb-ts/templates/ts/method.ejs:19:46)
    at method (/Users/r-maher/git/protoc-gen-jsonpb-ts/node_modules/ejs/lib/ejs.js:691:17)
    at include (/Users/r-maher/git/protoc-gen-jsonpb-ts/node_modules/ejs/lib/ejs.js:689:39)
    at service.methodList.forEach.method (/Users/r-maher/git/protoc-gen-jsonpb-ts/templates/ts/service.ejs:17:17)
    at Array.forEach (<anonymous>)
    at eval (/Users/r-maher/git/protoc-gen-jsonpb-ts/templates/ts/service.ejs:14:27)
    at service (/Users/r-maher/git/protoc-gen-jsonpb-ts/node_modules/ejs/lib/ejs.js:691:17)
    at include (/Users/r-maher/git/protoc-gen-jsonpb-ts/node_modules/ejs/lib/ejs.js:689:39)
    at serviceList.forEach.service (eval at compile (/Users/r-maher/git/protoc-gen-jsonpb-ts/node_modules/ejs/lib/ejs.js:661:12), <anonymous>:60:17)
    at Array.forEach (<anonymous>) path: '' }
--jsonpb-ts_out: protoc-gen-jsonpb-ts: Plugin failed with status code 2.
./example.sh  9.37s user 1.17s system 146% cpu 7.200 total
```

</details>

#34 makes the `Cannot read property 'http' of undefined` go away, but it has a different problem.  The output will be like 
```ts
/* GENERATED FROM example/basic/service/rpc-with-no-http-annotation.proto. DO NOT EDIT MANUALLY. */
/* tslint:disabled */
/* eslint-disable */

import { APIRequest, HTTPMethod } from "protoc-gen-jsonpb-ts";

import * as example_basic_dependency_dependency from "../../../example/basic/dependency/dependency_pb";

export namespace RPCWIthNoHTTPAnnotation {}
```

Which means there are unused imports, and [crashes the compiler in Typescript >=4](https://www.typescriptlang.org/play?#code/PQKgBA4gogclBKBBAKlAImAYvA8gWTAFMAPAQwFsAHAG0OACNSBnASwGNgnCAnAN3brdKbALQB3FgBcAFiIB2AexHTJkyiNJzFk0pJYK5AOkrcFkhYbBocYGDmRh0ASQd5EMAKqIAMt4CaliDAAFCgYJJM1CxykgBcACYsTKT0tPFgQaHghJHRkiKJyamEGSHBLFQK3JJgAN5giAAKTvCEAI4ArjmSADRgABLIyI14hDIK6QC+YABmpuRgAEQmZgqiAOaEciIAVkwGlPQiEYsA3MHlldUZYMxEZFS0APqMrGxP8YSUW59ybACeHy+Py2ANm8yWhkMwChMOhJAoNDor3YwE+3zkvwBaOBmNBgMOZwuJEoVRqcgoOUopDYJXgjQAwgB1JwyGAKQbDRBaMy6fRyOqTYJAA)
